spring:
  application:
    name: JoinClass
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

springdoc:
  swagger-ui:
    url: /openapi.yaml
    path: /swagger-ui.html